#!/usr/bin/env php
<?php
declare(strict_types=1);

use BackEndTea\Advent\DayProvider;

require_once __DIR__ . '/vendor/autoload.php';

(static function(array $args){
    $days = count($args) === 2 ?
        [DayProvider::provideDay((int) $args[1] -1)] :
        DayProvider::provideDays();


   foreach ($days as $day) {
       echo '===== Answering day ' . $day->number() . ' =====';
       echo "\n";
       echo 'Answer to challenge one: ';
       echo $day->solveChallengeOne(file_get_contents($day->getChallengeOneFile()));
       echo "\n\n";
       echo 'Answer to challenge two: ';
       echo $day->solveChallengeTwo(file_get_contents($day->getChallengeTwoFile()));
       echo "\n\n";
   }

})($argv);
